.github/workflows/build-push-docker.yaml

Fixed a small issue that seems to have been overseen during the migration to this repo

Fix Docker build action

---

.github/workflows/build-push-docker.yaml
Dockerfile.jupyterlab
jupyterlab/apt.txt
jupyterlab/environment.yaml
scripts/install-code-server.sh

- recent image-related changes made to qhub repo need to be copied over here.

Sync with qhub repo

---

.github/workflows/test-images.yaml
jupyterlab/postBuild

This was accidentally omitted from #11.

Install code-server from script

---

Dockerfile.dask-worker
Dockerfile.jupyterhub
Dockerfile.jupyterlab
scripts/install-conda.sh

Fixes https://github.com/nebari-dev/nebari-docker-images/issues/3

Swap out miniforge for mambaforge

---

jupyterlab/apt.txt

This is an original request originally made in https://github.com/Quansight/qhub/pull/1348, with the images now migrated those changes should me included in here.
I don't see any problem adding this to our images, as it's required for pyvista to work properly. Though we must discuss proper ways to update/add libs to these images in the future.

[ENH] Add xvfb to Jupyterlab env

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

- Bumps cdsdashboards version to use the latest version available on main, as there is no new release yet. The reason behind this update is due to the changes made in:
- https://github.com/ideonate/cdsdashboards/pull/104
- https://github.com/ideonate/cdsdashboards/pull/108
That is needed for the next update on Nebari.

Bump CDSDashboards to 0.6.3

---

.github/workflows/build-push-docker.yaml
jupyterlab/environment.yaml

Pin ipywidgets

---

jupyterhub/environment.yaml

- Updates navbar theme to include services such as conda-store, argo, ...

Bump qhub_jupyterhub_theme to 0.3.6

---

.github/workflows/build-push-docker.yaml

Update GHCR push token

---

.github/workflows/build-push-docker.yaml

Reverts nebari-dev/nebari-docker-images#29

Revert "Update GHCR push token"

---

.github/workflows/build-push-docker.yaml
.github/workflows/test-images.yaml
Dockerfile.dask-worker
Dockerfile.jupyterhub
Dockerfile.jupyterlab
README.md
dask-worker/environment.yaml
dask-worker/postBuild
jupyterhub/environment.yaml
jupyterhub/postBuild
jupyterlab/apt.txt
jupyterlab/environment.yaml
scripts/fix-permissions
scripts/install-apt-minimal.sh
scripts/install-apt.sh
scripts/install-code-server.sh
scripts/install-conda-environment.sh
scripts/install-conda.sh

- :memo: Update Readme
- :page_facing_up: Add license header
- 📦 Replace qhub theme for nebari theme

MAINT - Update dependencies and repo

---

.github/workflows/build-push-docker.yaml
README.md

- :memo: Add links to all the images
- :bug: Patch image tag

BUG - Fix image tag format

---

jupyterlab/environment.yaml

Fixes https://github.com/nebari-dev/nebari/issues/1539

Add ipympl to jupyterlab image

---

jupyterlab/environment.yaml

Remove the conda-store jlab ext for the upcoming release. This will be added back once the extension is ready.

Remove conda-store jlab ext (for now)

---

.github/workflows/build-push-docker.yaml
jupyterhub/environment.yaml

The new version of [sqlalchemy (2.0.0)](https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_0) released a few days ago appears to break JupyterHub. Here I am pinning sqlalchemy to the last version prior to their new release.

Pin sqlalchemy==1.4.46

---

jupyterlab/environment.yaml

Pin bokeh to pre 3.0.0

---

jupyterlab/environment.yaml

Bump the version of `jupyterlab-conda-store` package.

Update conda store UI

---

jupyterlab/environment.yaml

Add spellchecker and execute_time extensions

---

jupyterlab/environment.yaml

Remove execute time

---

.github/workflows/build-push-docker.yaml

add workflow_dispatch

---

nebari-workflow-controller/environment.yaml

pin version

---

jupyterlab/apt.txt

Include zsh

---

jupyterlab/environment.yaml

Adding jupyterlab-myst package with version constaint due to jupyterlab 3 vs. 4 issues

---

jupyterlab/environment.yaml

unpin jupyterlab_myst

---

jupyterlab/environment.yaml

Pin JLab to 4.0.2

---

jupyterlab/environment.yaml

Remove sidecar, retrolab

---

jupyterlab/environment.yaml

Remove jupyterlab-videochat

---

jupyterlab/environment.yaml
nebari-workflow-controller/environment.yaml

This is to include the packaged developed ([argo-jupyter-scheduler](https://github.com/nebari-dev/argo-jupyter-scheduler)) to use Argo-Workflows as a backend for Jupyter-Scheduler.

Add argo-jupyter-scheduler to JupyterLab image

---

.github/workflows/build-push-docker.yaml
jupyterlab/apt.txt

Closes https://github.com/nebari-dev/nebari/issues/2000

Add GPG + pinentry

---

jupyterlab/environment.yaml

Add jupyter_ai

---

.github/workflows/build-push-docker.yaml
.github/workflows/test-images.yaml

Upgrade images to CUDA 12

---

jupyterlab/environment.yaml

Pin ipywidgets greater than version 8

---

jupyterlab/environment.yaml

Remove jupyterlab conda-store extension from environment.

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Add jhub-apps 2024.1.2

---

jupyterlab/environment.yaml

Updates jhub to 4.0.2 in jlab image to match the jhub image,

update jhub in jlab container

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Moves jhub-apps into conda rather than pip.

move jhub-apps to conda

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Update `jhub-apps` to 2024.1.3

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Updates jhub apps to release 2024.1.5

update jhub apps

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Merge after this is merged: https://github.com/nebari-dev/jhub-apps/pull/122/files

Update jhub-apps to `2024.2.1rc1`

---

jupyterlab/environment.yaml

Adds https://github.com/nebari-dev/jupyterlab-nebari-mode (https://pypi.org/project/jupyterlab-nebari-mode/)
Closes https://github.com/nebari-dev/nebari/issues/2216

Add `jupyterlab-nebari-mode`

---

jupyterlab/environment.yaml

Addresses https://github.com/nebari-dev/nebari/pull/2267#issuecomment-1959788186
None

Pin jupyterlab-nebari-mode

---

jupyterlab/environment.yaml

Add `jupyterlab-favorites` extension

---

jupyterlab/environment.yaml

Closes https://github.com/nebari-dev/nebari/issues/2302
Reverts https://github.com/nebari-dev/nebari-docker-images/pull/104
Adding it in the `pip` section (as it was before) because there is no feedstock for it (https://github.com/conda-incubator/jupyterlab-conda-store/issues/48).

Add back `jupyterlab-conda-store`

---

jupyterlab/environment.yaml

- Needed for https://github.com/nebari-dev/nebari/issues/2326
- Includes https://github.com/nebari-dev/jupyterlab-nebari-mode/pull/2

Upgrade jupyterlab-nebari-mode to 0.3.0

---

jupyterlab/environment.yaml

Related to https://github.com/nebari-dev/argo-jupyter-scheduler/pull/7

Bump argo-jupyter-scheduler version

---

jupyterlab/environment.yaml

Relates to https://github.com/nebari-dev/nebari/issues/2241

Require latest jupyter-server which includes auth by default option

---

jupyterhub/environment.yaml

- Required for https://github.com/nebari-dev/nebari/issues/2308
- Supersedes https://github.com/nebari-dev/nebari-docker-images/pull/127
- Supersedes https://github.com/nebari-dev/nebari-docker-images/pull/128

Upgrade `oauthenticator` to 16.3.0

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Upgrade jhub-apps to 2024.4.1

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

https://github.com/nebari-dev/nebari/issues/2330

Upgrade JupyterHub to 5.0.0b1

---

jupyterlab/environment.yaml

- https://github.com/conda-incubator/conda-store-ui/issues/255
- https://github.com/nebari-dev/jupyterlab-new-launcher
(for now this is a draft for testing the image including `jupyterlab-new-launcher`, and also for awareness)
TBD

Add `jupyterlab-new-launcher` extension

---

jupyterlab/environment.yaml

Fixes CI integration test failing on `nebari` main branch

Upgrade `jupyterlab-new-launcher` to 0.3.2

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

- follow-up to https://github.com/nebari-dev/nebari-docker-images/pull/140
- https://github.com/nebari-dev/nebari/issues/2330
- sibling to https://github.com/nebari-dev/nebari/pull/2468

Upgrade JupyterHub to 5.0.0b2

---

jupyterlab/environment.yaml

Fixes a number of issues, see https://github.com/nebari-dev/jupyterlab-new-launcher/releases/tag/v0.3.3 for changelog

Upgrade `jupyterlab-new-launcher` to 0.3.3

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

- follow-up to https://github.com/nebari-dev/nebari-docker-images/pull/145
- https://github.com/nebari-dev/nebari/issues/2330
- sibling to https://github.com/nebari-dev/nebari/pull/TBD

Upgrade JupyterHub to 5.0.0 final

---

jupyterhub/environment.yaml

Pin nebari-jupyterhub-theme to latest version.

---

jupyterlab/environment.yaml

Follow-up to https://github.com/nebari-dev/nebari-docker-images/pull/147, includes a fix for the last issue that we wanted to address before shipping (https://github.com/nebari-dev/jupyterlab-new-launcher/issues/31)

Upgrade `jupyterlab-new-launcher` to 0.4.1

---

jupyterlab/environment.yaml

Fixes a regression with environment column not showing up

Upgrade `jupyterlab-new-launcher` to 0.4.2

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Bump jhub-apps version to latest RC.

---

jupyterlab/environment.yaml

Bump argo-jupyter-scheduler version to latest RC.

---

jupyterlab/environment.yaml

https://github.com/jupyterhub/jupyter-server-proxy/security/advisories/GHSA-fvcq-4x64-hqxr
https://jupyter-server-proxy.readthedocs.io/en/latest/changelog.html#v4-2-0-2024-06-11

Require `jupyter-server-proxy` 4.2.0 or newer

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Following the release: https://github.com/nebari-dev/jhub-apps/pull/339#issuecomment-2165917603

Bump jhub-apps to `2024.6.1`

---

jupyterlab/environment.yaml

https://github.com/nebari-dev/nebari/issues/2456

Add `jupyterlab-gallery` extension

---

jupyterlab/environment.yaml

Add jupyterlab_nvdashboard

---

jupyterlab/environment.yaml

This version jump brings:
- one enhancement https://github.com/nebari-dev/jupyterlab-new-launcher/pull/52
- bug fixes:
- for https://github.com/nebari-dev/jupyterlab-new-launcher/issues/51 which was designated as a blocker for nebari release by @marcelovilla 
- https://github.com/nebari-dev/jupyterlab-new-launcher/pull/57
- https://github.com/nebari-dev/jupyterlab-new-launcher/pull/56
- https://github.com/nebari-dev/jupyterlab-new-launcher/pull/55

Update `jupyterlab-new-launcher` to v0.5.1

---

jupyterlab/environment.yaml

Update argo-jupyter-scheduler to include official release.

---

jupyterlab/environment.yaml

Includes an urgent hotfix for cloning not working on some nebari instances (https://github.com/nebari-dev/jupyterlab-gallery/issues/26), improved UX and a host of bug fixes.
- https://github.com/nebari-dev/jupyterlab-gallery/releases/tag/v0.3.0
- https://github.com/nebari-dev/jupyterlab-gallery/releases/tag/v0.3.1
- https://github.com/nebari-dev/jupyterlab-gallery/releases/tag/v0.3.2

Upgrade `jupyterlab-gallery` to version `0.3.2`

---

jupyterlab/environment.yaml

https://github.com/nebari-dev/jupyterlab-gallery/releases/tag/v0.3.3 - just a minor bug fix to ensure placeholder icons for GitHub get displayed reliably on nebari

Upgrade `jupyterlab-gallery` to version `0.3.3`

---

jupyterlab/environment.yaml

- [v0.4.0](https://github.com/nebari-dev/jupyterlab-gallery/releases/tag/v0.4.0) adds `branch` and `depth` options
- sibling to https://github.com/nebari-dev/nebari/pull/2556

Upgrade `jupyterlab-gallery` to version `0.4.0`

---

jupyterlab/environment.yaml

https://github.com/nebari-dev/nebari/issues/2523

Update `jupyterlab-conda-store` to 2024.6.1

---

jupyterhub/environment.yaml

Bump `nebari-jupyterhub-theme` version to `2024.7.1`

---

jupyterlab/environment.yaml

See https://github.com/nebari-dev/nebari/issues/2600 for a reference

Revert conda-store plugin version to 2024.3.1

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Upgrade jhub-apps to `2024.7.1`

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Upgrade jhub-apps to `2024.8.1`

---

jupyterlab/environment.yaml

Closes https://github.com/nebari-dev/nebari/issues/2580

Raise `pyviz_comms` and `bokeh` pins

---

jupyterlab/environment.yaml

Required for https://github.com/nebari-dev/nebari/pull/2590

Update `jupyterlab-gallery` pin to 0.6.3

---

jupyterlab/environment.yaml

Pre-requisite for https://github.com/nebari-dev/nebari/pull/2590

Require `jupyter-server-proxy` 4.4.0 or newer

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

See release: https://github.com/nebari-dev/jhub-apps/releases/tag/2024.10.1

Update jhub-apps to `2024.10.1`

---

jupyterlab/environment.yaml

Given that [Jupyterlab 4.3 was recently released](https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v4-3), and that it [could have side-effects on existing extensions](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#css-styling), we're pinning jupyterlab to 4.2.5, the version we were using in the latest release of the docker images. This will allow us to release a [hotfix for Nebari 2024.9.1](https://github.com/nebari-dev/nebari/issues/2798) without worrying about other things potentially breaking.

Pin jupyterlab version

---

jupyterlab/environment.yaml

- Includes a fix for https://github.com/nebari-dev/jupyterlab-launchpad/issues/68
- That's the only change, see https://github.com/nebari-dev/jupyterlab-launchpad/releases/tag/v1.0.3

Bump `jupyterlab-launchpad` to `v1.0.3`

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Upgrade jhub-apps to `2024.11.1`

---

jupyterlab/environment.yaml

Bump conda-store extension version to 2024.11.1

---

jupyterlab/environment.yaml

Pulls some things like:
- https://github.com/rapidsai/jupyterlab-nvdashboard/pull/202
- https://github.com/rapidsai/jupyterlab-nvdashboard/pull/201

Update `jupyterlab-nvdashboard` to 0.12.0

---

jupyterlab/environment.yaml

This PR pins `ipympl` in the jupyterlab conda environment as the building of the jupyterlab docker images started [failing spontaneously](https://github.com/nebari-dev/nebari-docker-images/actions/runs/13653458834/job/38167111841).

Pin ipympl in jupyterlab conda environment

---

jupyterlab/environment.yaml

Upgrade JupyterLab to 4.4

---

jupyterhub/environment.yaml
jupyterlab/environment.yaml

Companion PR: https://github.com/nebari-dev/nebari/pull/3052

Upgrade JupyterHub to 5.3.0
